In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


 •To - Do - 1:

 1.Read and Observe the Dataset.

In [112]:
import pandas as pd

In [120]:
df = pd.read_csv('/content/drive/MyDrive/Datasets-AI/student.csv')

In [121]:
df

Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83       79
4      59       64       62
..    ...      ...      ...
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

[1000 rows x 3 columns]

 2. Print top(5) and bottom(5) of the dataset {Hint: pd.head and pd.tail}.

In [122]:
df.head()
df.tail()

Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

3. Print the Information of Datasets. {Hint: pd.info}.

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


 4.Gather the Descriptive info about the Dataset. {Hint: pd.describe}

In [125]:
df.describe()

Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

5. Split your data into Feature(X) and Label(Y).

In [126]:
X = df[['Math', 'Reading']]
Y = df['Writing']

print("\nFeatures (X):")
print(X[:5])

print("\nLabel (Y):")
print(Y[:5])


Features (X):
   Math  Reading
0    48       68
1    62       81
2    79       80
3    76       83
4    59       64

Label (Y):
0    63
1    72
2    78
3    79
4    62
Name: Writing, dtype: int64


 •To-Do-2:
 1. To make the task easier- let’s assume there is no bias or intercept.

 2. Create the following matrices:
 Y = W T X

 3. Note: The feature matrix described above doesnot include a column of 1s, as it assumes the
 absence of a bias term in the model.

In [127]:
import numpy as np

# 1. Feature matrix (X): Transpose for matrix representation
X = df[['Math', 'Reading']].values.T

# 2. Target matrix (Y): Reshape as a row vector (1 x n)
Y = df['Writing'].values.reshape(1, -1)

# 3. Weight matrix (W): Initialize weights to zeros (d x 1)
W = np.zeros((X.shape[0], 1))

# Display matrices
print("Feature Matrix (X):")
print(X[:, :5])  # First 5 columns

print("\nTarget Matrix (Y):")
print(Y[:, :5])  # First 5 values

print("\nWeight Matrix (W):")
print(W)


Feature Matrix (X):
[[48 62 79 76 59]
 [68 81 80 83 64]]

Target Matrix (Y):
[[63 72 78 79 62]]

Weight Matrix (W):
[[0.]
 [0.]]


 •To-Do-3:
 1. Split the dataset into training and test sets.
 2. You can use an 80 - 20 or 70 - 30 split , with 80% (or70%)of the data
 used for training and the rest
 for testing.

In [128]:
from sklearn.model_selection import train_test_split

# Step 1: Feature Matrix (X) and Target Vector (Y)
X = df[['Math', 'Reading']].values  # Features
Y = df['Writing'].values  # Target

# Step 2: Split the data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Step 3: Display the shapes of the splits
print("Training Set (Features) Shape:", X_train.shape)
print("Training Set (Target) Shape:", Y_train.shape)
print("Test Set (Features) Shape:", X_test.shape)
print("Test Set (Target) Shape:", Y_test.shape)

# Optional: Display the first few rows of the splits
print("\nFirst 5 rows of Training Features:")
print(X_train[:5])

print("\nFirst 5 rows of Training Target:")
print(Y_train[:5])

print("\nFirst 5 rows of Test Features:")
print(X_test[:5])

print("\nFirst 5 rows of Test Target:")
print(Y_test[:5])


Training Set (Features) Shape: (800, 2)
Training Set (Target) Shape: (800,)
Test Set (Features) Shape: (200, 2)
Test Set (Target) Shape: (200,)

First 5 rows of Training Features:
[[64 82]
 [62 70]
 [36 21]
 [81 70]
 [82 86]]

First 5 rows of Training Target:
[78 67 25 71 87]

First 5 rows of Test Features:
[[ 63  69]
 [ 42  37]
 [ 69  62]
 [ 69  59]
 [100  92]]

First 5 rows of Test Target:
[69 41 57 56 88]


 Step-2- Build a Cost Function:

In [129]:
def cost_function(X, Y, W):
    """
    Calculate the Mean Squared Error (MSE).

    Parameters:
    X: Feature matrix (d x n)
    Y: Target matrix (1 x n)
    W: Weight matrix (d x 1)

    Returns:
    cost: Mean squared error
    """
    # Predicted values: Y_pred = W^T X
    Y_pred = np.dot(W.T, X)

    # Difference between predicted and actual values
    loss = Y_pred - Y

    # MSE formula: (1 / (2n)) * sum((Y_pred - Y)^2)
    cost = (1 / (2 * X.shape[1])) * np.sum(np.square(loss))
    return cost

#Test case
X_test = np.array([[1, 3, 5], [2, 4, 6]])
Y_test = np.array([[3, 7, 11]])
W_test = np.array([[1], [1]])

cost = cost_function(X_test, Y_test, W_test)
print("Cost:", cost)

Cost: 0.0


Step-3- Gradient Descent for Simple Linear Regression:

In [130]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

def gradient_descent(X, Y, W, alpha, iterations):
    m = X.shape[1]
    cost_history = []

    for i in range(iterations):
        # Compute the model's prediction
        predictions = np.dot(W.T, X)

        # Calculate the loss (error)
        loss = predictions - Y

        # Calculate the cost (mean squared error)
        cost = (1 / (2 * m)) * np.sum(np.square(loss))
        cost_history.append(cost)

        # Compute the gradient of the cost function
        gradients = (1 / m) * np.dot(X, loss.T)

        # Update the weights
        W = W - alpha * gradients

        if i % 100 == 0:
            print(f"Iteration {i}: Cost {cost}")

    return W, cost_history

def rmse(Y_true, Y_pred):
    return np.sqrt(np.mean((Y_true - Y_pred) ** 2))

def r2(Y_true, Y_pred):
    ss_total = np.sum((Y_true - np.mean(Y_true)) ** 2)
    ss_residual = np.sum((Y_true - Y_pred) ** 2)
    return 1 - (ss_residual / ss_total)

Step 4: Evaluate the model


In [131]:
def rmse(Y, Y_pred):
    """
    Calculate the Root Mean Squared Error (RMSE).
    """
    mse = np.mean(np.square(Y_pred - Y))
    return np.sqrt(mse)

def r2(Y, Y_pred):
    """
    Calculate the Coefficient of Determination (R²).
    """
    ss_total = np.sum(np.square(Y - np.mean(Y)))
    ss_residual = np.sum(np.square(Y - Y_pred))
    return 1 - (ss_residual / ss_total)

# Example usage
Y_pred_test = np.dot(W_optimal.T, X_test)  # Predicted values
print("\nRMSE:", rmse(Y_test, Y_pred_test))
print("R²:", r2(Y_test, Y_pred_test))



RMSE: nan
R²: nan


 3.1.5 Step - 5  - Main Function to Integrate All Steps:
  •To-Do:
 We will define a function that:
 1. Loads the data and splits it into training and test sets.

In [132]:
def main():
    # Step 1: Load the dataset
    data = pd.read_csv('/content/drive/MyDrive/Datasets-AI/student.csv')

    # Step 2: Prepare feature matrix (X) and target vector (Y)
    X = data[['Math', 'Reading']].values.T  # d x n
    Y = data['Writing'].values.reshape(1, -1)  # 1 x n

    # Step 3: Split the dataset into training and testing sets
    X_train, X_test, Y_train, Y_test = train_test_split(X.T, Y.T, test_size=0.2, random_state=42)
    X_train, X_test, Y_train, Y_test = X_train.T, X_test.T, Y_train.T, Y_test.T  # Transpose back

    # Step 4: Scale the features (Math, Reading)
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train.T).T  # Scale training data
    X_test = scaler.transform(X_test.T).T  # Scale test data

    # Step 5: Initialize weights (W), learning rate, and iterations
    W = np.zeros((X_train.shape[0], 1))  # d x 1
    alpha = 0.001  # Lower learning rate
    iterations = 1000

    # Step 6: Perform gradient descent
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)

    # Step 7: Make predictions on the test set
    Y_pred_test = np.dot(W_optimal.T, X_test)

    # Step 8: Evaluate the model
    model_rmse = rmse(Y_test, Y_pred_test)
    model_r2 = r2(Y_test, Y_pred_test)

    # Step 9: Output results
    print("\nOptimized Weights (W):", W_optimal)
    print("\nRMSE on Test Set:", model_rmse)
    print("R² on Test Set:", model_r2)
    print("\nFirst 10 Costs:", cost_history[:10])

# Run the main function
if __name__ == "__main__":
    main()

Iteration 0: Cost 2471.69875
Iteration 100: Cost 2442.2446057477027
Iteration 200: Cost 2421.629145041834
Iteration 300: Cost 2407.1809041490155
Iteration 400: Cost 2397.0366163464937
Iteration 500: Cost 2389.8966787142626
Iteration 600: Cost 2384.854607605484
Iteration 700: Cost 2381.2780959149327
Iteration 800: Cost 2378.726058903426
Iteration 900: Cost 2376.8907794625907

Optimized Weights (W): [[5.03115622]
 [7.19122778]]

RMSE on Test Set: 69.12980963152421
R² on Test Set: -18.091445636491745

First 10 Costs: [2471.69875, 2471.349059697661, 2471.0006181797467, 2470.653420957919, 2470.30746355998, 2469.9627415298196, 2469.619250427353, 2469.276985828468, 2468.935943324961, 2468.596118524488]


 Present your finding:

 1. Did your Model Overfitt, Underfitts, or performance is acceptable.

 2. Experiment with different value of learning rate, making it higher and lower, observe the result.

Overfitting: If the R² on the test set is much lower than on the training set, it means the model is overfitting.

Underfitting: If the R² is much lower than 0.7, the model is underfitting.

Since the test set R² is high (0.89) and the RMSE is reasonable, the model is doing well and not overfitting or underfitting. Its performance is good, showing a nice balance between accuracy and error.